# Generated by Django 5.1 on 2025-04-22 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cloth",
            fields=[
                ("cloth_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "Double Extra Large"),
                        ],
                        max_length=3,
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("material", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                ("rent_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("availability", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("img", models.ImageField(upload_to="cloth_images/")),
                ("date_added", models.DateField(auto_now=True)),
                (
                    "user_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
