# Generated by Django 5.1 on 2025-04-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_cloth"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloth",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
