# Generated by Django 5.1 on 2025-04-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_cloth_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselImages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="carousel_images/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("priority", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
