# Generated by Django 5.1 on 2025-04-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_carouselimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselimages",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
